version: '3.8'

networks:
  internal:
    driver: bridge

services:
  gateway:
    build: .
    environment:
      ENV_FILE_NAME: values_prod.yaml
    ports:
      - "8080:8080"
    networks:
      - internal
    # entrypoint: ["make", "run"]
    command: tail -F anything
    depends_on:
     - keydb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 15s
  keydb:
    image: eqalpha/keydb
    restart: always
    ports:
      - '6379:6379'
    networks:
      - internal
  