version: '3.8'

networks:
  internal:
    driver: bridge

# volumes:
#  db:
#    driver: local
#    driver_opts:
#      device: ./database
#      o: bind
#       type: local

services:
  backend:
    build: .
    environment:
      ENV_FILE_NAME: values_prod.yaml
    ports:
      - "8080:8080"
    networks:
      - internal
    entrypoint: ["make", "run"]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 15s
  keydb:
    image: eqalpha/keydb
    restart: always
    ports:
      - '6379:6379'
    networks:
      - internal
  