basePath: /api
definitions:
  github_com_whitewolf185_SystemArchitecture_domain-service_api_domain.Companion:
    properties:
      client_id:
        type: string
      destination:
        type: string
    type: object
  github_com_whitewolf185_SystemArchitecture_domain-service_api_domain.CreateCompanionRequestPayload:
    properties:
      client_id:
        type: string
      destination:
        type: string
    type: object
  github_com_whitewolf185_SystemArchitecture_domain-service_api_domain.CreateRouteRequestPayload:
    properties:
      client_id:
        type: string
      path:
        items:
          type: string
        type: array
    type: object
  github_com_whitewolf185_SystemArchitecture_domain-service_api_domain.Route:
    properties:
      client_id:
        type: string
      path:
        items:
          type: string
        type: array
    type: object
  github_com_whitewolf185_SystemArchitecture_domain-service_pkg_custom_errors.ErrCodes:
    properties:
      code:
        type: integer
      err: {}
    type: object
info:
  contact: {}
  description: swagger для api к клиентскому сервису
  title: Client service
  version: '@0.9'
paths:
  /domain/CreateCompanion:
    post:
      consumes:
      - application/json
      description: создание попутчика. У пользователя не получится создать несколько
        сущностей попутчиков
      operationId: domain_service_create_companion
      parameters:
      - description: Параметры, по которым создаем информацию
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_whitewolf185_SystemArchitecture_domain-service_api_domain.CreateCompanionRequestPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_whitewolf185_SystemArchitecture_domain-service_api_domain.Companion'
        default:
          description: ""
          schema:
            $ref: '#/definitions/github_com_whitewolf185_SystemArchitecture_domain-service_pkg_custom_errors.ErrCodes'
      tags:
      - domain_service
  /domain/CreateRoute:
    post:
      consumes:
      - application/json
      description: создание маршрута. Водителю не получится создать несколько маршрутов.
        Сущность маршрутов будет одна, но в нее можно будет поместить несколько пунктов
        назначения.
      operationId: domain_service_create_route
      parameters:
      - description: Параметры, по которым создаем информацию
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_whitewolf185_SystemArchitecture_domain-service_api_domain.CreateRouteRequestPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_whitewolf185_SystemArchitecture_domain-service_api_domain.Route'
        default:
          description: ""
          schema:
            $ref: '#/definitions/github_com_whitewolf185_SystemArchitecture_domain-service_pkg_custom_errors.ErrCodes'
      tags:
      - domain_service
  /domain/DeleteCompanion:
    delete:
      consumes:
      - application/json
      description: Удаление сущности попутчика у пользователя.
      operationId: domain_service_delete_companion
      parameters:
      - in: query
        name: client_id
        type: string
      produces:
      - application/json
      responses:
        default:
          description: ""
          schema:
            $ref: '#/definitions/github_com_whitewolf185_SystemArchitecture_domain-service_pkg_custom_errors.ErrCodes'
      tags:
      - domain_service
  /domain/DeleteRoute:
    delete:
      consumes:
      - application/json
      description: Удаление сущности маршрута у пользователя.
      operationId: domain_service_delete_route
      parameters:
      - in: query
        name: client_id
        type: string
      produces:
      - application/json
      responses:
        default:
          description: ""
          schema:
            $ref: '#/definitions/github_com_whitewolf185_SystemArchitecture_domain-service_pkg_custom_errors.ErrCodes'
      tags:
      - domain_service
  /domain/GetCompanionInfo:
    get:
      consumes:
      - application/json
      description: получение попутчика по фильтрам.
      operationId: domain_service_get_companion_info
      parameters:
      - in: query
        name: client_id
        type: string
      - in: query
        name: destination
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_whitewolf185_SystemArchitecture_domain-service_api_domain.Companion'
            type: array
        default:
          description: ""
          schema:
            $ref: '#/definitions/github_com_whitewolf185_SystemArchitecture_domain-service_pkg_custom_errors.ErrCodes'
      tags:
      - domain_service
  /domain/GetRouteInfo:
    get:
      consumes:
      - application/json
      description: получение маршрута по фильрам.
      operationId: domain_service_get_route_info
      parameters:
      - in: query
        name: client_id
        type: string
      - in: query
        name: one_of_path
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_whitewolf185_SystemArchitecture_domain-service_api_domain.Route'
            type: array
        default:
          description: ""
          schema:
            $ref: '#/definitions/github_com_whitewolf185_SystemArchitecture_domain-service_pkg_custom_errors.ErrCodes'
      tags:
      - domain_service
swagger: "2.0"
