version: '3.8'

networks:
  internal:
    driver: bridge

services:
  mongo-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27016:27017'
    networks:
      - internal
    volumes:
      - ./database:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
  domain-service:
    build: .
    environment:
      ENV_FILE_NAME: values_prod.yaml
    ports:
      - "8081:8081"
    networks:
      - internal
    depends_on:
      - db
    entrypoint: ["make", "run"]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 15s
  