version: '3.8'

networks:
  internal:
    driver: bridge

# volumes:
#  db:
#    driver: local
#    driver_opts:
#      device: ./database
#      o: bind
#       type: local

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=client_service
    ports:
      - '5433:5432'
    networks:
      - internal
    volumes:
      - ./database:/var/lib/postgresql/data
  backend:
    build: .
    environment:
      ENV_FILE_NAME: values_prod.yaml
      PGPASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - internal
    depends_on:
      - db
    entrypoint: ["make", "run"]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 15s
  