// Code generated by "stringer -type=HandlerType -output=./handler_types_string.go"; DO NOT EDIT.

package domain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GetClientByID-0]
	_ = x[CreateUser-1]
	_ = x[SearchUserByUserName-2]
	_ = x[DeleteUserByID-3]
	_ = x[Login-4]
}

const _HandlerType_name = "GetClientByIDCreateUserSearchUserByUserNameDeleteUserByIDLogin"

var _HandlerType_index = [...]uint8{0, 13, 23, 43, 57, 62}

func (i HandlerType) String() string {
	if i < 0 || i >= HandlerType(len(_HandlerType_index)-1) {
		return "HandlerType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HandlerType_name[_HandlerType_index[i]:_HandlerType_index[i+1]]
}
